 main = ".open-next/worker.js"
  name = "admin_logistic"
  compatibility_date = "2025-03-25"
  compatibility_flags = ["nodejs_compat"]
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"
  [vars]
  NEXT_PUBLIC_BASE_URL="http://vntranspbackend-production.up.railway.app/v1"
  UPLOADTHING_TOKEN="eyJhcGlLZXkiOiJza19saXZlXzljYWJjMDhiZGYxYjcxYjIwMDNmYzc5M2E3NmIxZjcxYzI1YTJlMzhhYzE3ZjQ3YmNkZmJjMTdhOWJmMDgwMzQiLCJhcHBJZCI6Im9xeGRwb29zZHgiLCJyZWdpb25zIjpbInNlYTEiXX0="
  NEXT_PUBLIC_UPLOADTHING_API_KEY= "eyJhcGlLZXkiOiJza19saXZlXzljYWJjMDhiZGYxYjcxYjIwMDNmYzc5M2E3NmIxZjcxYzI1YTJlMzhhYzE3ZjQ3YmNkZmJjMTdhOWJmMDgwMzQiLCJhcHBJZCI6Im9xeGRwb29zZHgiLCJyZWdpb25zIjpbInNlYTEiXX0="

  [observability.logs]
  enabled = true